apiVersion: v1
kind: Service
metadata:
  name: app-sag-service
spec:
  type: NodePort
  ports:
  - port: 5555
  selector:
    app: app-sag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sag-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-sag
  template:
    metadata:
      labels:
        app: app-sag
    spec:
      containers:
      - name: sagmsr
        image: store/softwareag/webmethods-microservicesruntime:10.5
        ports:
        - containerPort: 5555